### ISSUE TITLE
Erreur dans le type de retour

### ISSUE THREAD

**Issue by cegerard** [TerenceHilderal/d2vlop#2]
https://github.com/TerenceHilderal/d2vlop/blob/ff4b18640ce923258cf42114181b01b2e369eceb/index.js#L33

Ici ta fonction retourne un tableau contenant tout les éléments avec le label passé en paramètre.
Mais dans l'énnoncé on attend un seul élément en sortie.

**Comment by TerenceHilderal** [comment]
ici il doit me retourner le premier élément trouvé avec le label recherché?

**Comment by cegerard** [comment]
Oui par exemple.
