### ISSUE TITLE
Execution

### ISSUE THREAD

**Issue by cegerard** [TerenceHilderal/d2vlop#3]
Comment as-tu testé tes fonctions ?
Tu les a exécuter sur les différents tableaux que je t'ai donnée ?

**Comment by TerenceHilderal** [comment]
J'ai copié un bout de tableau seulement

**Comment by cegerard** [comment]
Oui c'est ce que je me suis dis.
Il faut que tu essaies avec les trois tableaux c'est important. Ils ont des tailles biens différentes justement pour illustrer l'impact que cela peut avoir sur tes perfs.

**Comment by TerenceHilderal** [comment]
Ah d'accord, et du coup faut que les fichiers en format json je les transforme en js ?

**Comment by cegerard** [comment]
Oui, tu peux charger ton fichier JSON depuis ton code JS et le parser en JS ensuite.

**Comment by TerenceHilderal** [comment]
faut que je fasse une requête ajax pour pouvoir charger mon fichier json depuis mon code js?

**Comment by cegerard** [comment]
Non ajax il te faut un serveur. Là tu peux simplement charger ton fichier depuis le disque. En js tu as des fonction pour ça. Tu n'es pas obligé de faire les exos dans un navigateur, tu peux faire du NodeJS
