### ISSUE TITLE
Code brut

### ISSUE THREAD

**Issue by cegerard** [TerenceHilderal/d2vlop#4]
Serais-tu capables de réécrire ces fonctions sans utiliser les méthodes proposées par Array de javascript ?

**Comment by TerenceHilderal** [comment]
Sans filter ou for each?

**Comment by cegerard** [comment]
oui, pour écrire l'algo de base.
En sachant qu'a la mains tu peux faire plus optimisé qu'avec filter.

**Comment by TerenceHilderal** [comment]
D'accord je vais essayer ça
