### ISSUE TITLE
Variable globale

### ISSUE THREAD

**Issue by cegerard** [TerenceHilderal/d2vlop#5]
https://github.com/TerenceHilderal/d2vlop/blob/41733fe2f7e4739b93b91a753eddb57284c3c16b/index.js#L16

Ta variable est global à ton fichier.
Que se passe t-il si tu lances différentes recherche à la suite ?

**Comment by TerenceHilderal** [comment]
le mieux serait d'utiliser les variables locales? que ça interfère pas avec le code extérieure à la fonction?

**Comment by cegerard** [comment]
Oui, de manière général il ne faut pas utiliser de variable globale.
Tu ne peux pas maitriser qui manipule cette variable et comme dans ton code tu peux te retrouver avec un comportement étrange et des résultats erronés en fonction de comment tes fonctions sont appeler.

Un bonne pratique c'est d'éviter tout effet de bord dans tes fonctions. Elles ne doivent dépendre que de leurs paramètres ou des variables d'instance pour une méthode de classe.
