### ISSUE TITLE
Optimisation 2

### ISSUE THREAD

**Issue by cegerard** [TerenceHilderal/d2vlop#7]
https://github.com/TerenceHilderal/d2vlop/blob/41733fe2f7e4739b93b91a753eddb57284c3c16b/index.js#L45

Pareil ici.
Tu peux être beaucoup plus efficace.
Tu n'as pas besoin de parcourir tout le tableau et de copier l'ensemble des éléments.
Tu peux tout faire dans la même itération et d'arréter dès que tu as trouvé ce que tu cherchais.

**Comment by TerenceHilderal** [comment]
il me reste celui là à faire
