### ISSUE TITLE
Optimisation 3

### ISSUE THREAD

**Issue by cegerard** [TerenceHilderal/d2vlop#8]
https://github.com/TerenceHilderal/d2vlop/blob/41733fe2f7e4739b93b91a753eddb57284c3c16b/index.js#L62

Attention ici tu copies tout les éléments dans un tableau alors que tu ne veux que le dernier.
Tu n'as pas besoin d'utiliser un tableau mais simplement de conserver l'élément courant.

**Comment by TerenceHilderal** [comment]
hello, j'y arrive pas je comprend pas comment je peux faire ressortir le dernier element  qui contient la valeur voulu sans utiliser de tableau

**Comment by TerenceHilderal** [comment]
car la si je ne push pas dans un tableau il me ressort le premier objet du tableau avec l'attribut demandé

**Comment by cegerard** [comment]
Pose toi la question qu'est-ce que tu essais de faire ressortir ?
Tu utilises un tableau pour ton résultat, mais est-ce que tu veux ressortir un tableau ?
Non, au final tu veux ressortir un seul élément, donc tu peux sauvegarder le dernier élément trouvé à chaque fois.
Et le remplacer chaque fois que ta condition est bonne.

**Comment by TerenceHilderal** [comment]
pour celui-ci c'est bon
